health = '/api/health'
lists = '/api/lists'
lst = '/api/lists/{list_id}'
subscriber = '/api/subscribers/{subscriber_id}'
subscribers = '/api/subscribers'
opt_in = '/subscription/optin/{subscriber_uuid}'
send_tx = '/api/tx'
